

@version = 
@h = localhost
@path = 
@p = 23000


POST   http://{{h}}:{{p}}/getDistrict_by_provinceID?q=10 HTTP/1.1
Content-Type: application/json
Token:11111111
Authorization:dba123456

{ 
    "pr_id":1
}
