CREATE DATABASE IF NOT EXISTS strapi_dbk;
use strapi_dbk;
CREATE USER 'adminstrapi_dbk'@'%' IDENTIFIED BY 'mVXQhy6yTRdTfrgh';
GRANT ALL PRIVILEGES ON *.* TO 'adminstrapi_dbk'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";