version: "3.7"
services:
  # mysql
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - mysqldb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5martH67
      MYSQL_USER: dbadminvms
      MYSQL_PASSWORD: rpXyV8TaL2F4ZHaY
    ports:
      - 3306:3306
    networks:
      - mysqldb_network
  
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: 5martH67
    ports:
      - 8080:80
    networks:
      - mysqldb_network

volumes:
  mysqldb_data:
networks:
  mysqldb_network: