version: "3.7"
services:
  vdpapi:
    build: . 
    restart: always
    container_name: vdpapi
    ports:
      - 23000:23000
    environment:
      - DATABASE_HOST=host.docker.internal
    volumes:
      - .:/app